version: "3.5"
services:
  reports:
    build:
      context: .
    stdin_open: true
    tty: true
    container_name: pca-pdf-report
    hostname: pca-report
    restart: unless-stopped
    ports:
      - "3030:3030"
    networks:
      - frontend
      - backend
    env_file:
      - .env
  browserless:
    image: browserless/chrome:latest
    container_name: pca-browserless
    environment:
      - "MAX_CONCURRENT_SESSIONS=10"
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend

networks:
  frontend:
    name: pca_frontend
  backend:
    name: pca_backend
